# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "nvme"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/NixOS-Root";
    # label = "Root";
    fsType = "ext4";
    encrypted = {
      enable = true;
      blkDev = "/dev/disk/by-uuid/c940fd8d-919b-4cf0-9f1f-88ec3b5e48cf";
      label = "NixOS";
    };
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/Boot";
    label = "Boot";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/NixOS-Swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
